# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'camera_show.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(512, 512)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(512, 512))
        Form.setCursor(QtGui.QCursor(QtCore.Qt.UpArrowCursor))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.graphicsView = QtWidgets.QGraphicsView(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.autoScaleCheckBox = QtWidgets.QCheckBox(Form)
        self.autoScaleCheckBox.setObjectName("autoScaleCheckBox")
        self.horizontalLayout.addWidget(self.autoScaleCheckBox)
        self.liveButton = QtWidgets.QPushButton(Form)
        self.liveButton.setObjectName("liveButton")
        self.horizontalLayout.addWidget(self.liveButton)
        self.SnapButton = QtWidgets.QPushButton(Form)
        self.SnapButton.setObjectName("SnapButton")
        self.horizontalLayout.addWidget(self.SnapButton)
        self.histoButton = QtWidgets.QPushButton(Form)
        self.histoButton.setObjectName("histoButton")
        self.horizontalLayout.addWidget(self.histoButton)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.autoScaleCheckBox.setText(_translate("Form", "AutoScale"))
        self.liveButton.setText(_translate("Form", "Live"))
        self.SnapButton.setText(_translate("Form", "Snap"))
        self.histoButton.setText(_translate("Form", "Histogram"))
